// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoKlLb0XNbS7odo7ptH5De7RyNinDBU48',
    appId: '1:185220043575:web:31a85e12be41b69442c0b2',
    messagingSenderId: '185220043575',
    projectId: 'authentication-demo-cca56',
    authDomain: 'authentication-demo-cca56.firebaseapp.com',
    storageBucket: 'authentication-demo-cca56.appspot.com',
    measurementId: 'G-YEZT1M1J45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlynjFXj12cKZJkD3N8ZKFSGu6zfKmt0o',
    appId: '1:185220043575:android:5670dd171b48fd3d42c0b2',
    messagingSenderId: '185220043575',
    projectId: 'authentication-demo-cca56',
    storageBucket: 'authentication-demo-cca56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWqU7g4051LU2_Dg1mUa8uy1F558G9zKk',
    appId: '1:185220043575:ios:70e14df4f93d0bf042c0b2',
    messagingSenderId: '185220043575',
    projectId: 'authentication-demo-cca56',
    storageBucket: 'authentication-demo-cca56.appspot.com',
    iosClientId: '185220043575-9mg3ppscp6idfo4g7rtr3aphjsurq0n3.apps.googleusercontent.com',
    iosBundleId: 'com.laxit.authenticationsDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWqU7g4051LU2_Dg1mUa8uy1F558G9zKk',
    appId: '1:185220043575:ios:0a9395d8fbb0a12642c0b2',
    messagingSenderId: '185220043575',
    projectId: 'authentication-demo-cca56',
    storageBucket: 'authentication-demo-cca56.appspot.com',
    iosClientId: '185220043575-6hrpgqbcfsgldmhto3nl6a814e4pev9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationsDemo',
  );
}
